name: FTF Engineering
favicon: null
layout_spectrum: 0
typography_spectrum: 0.434276235755533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#354c6c'
    - '#c1c8ce'
    - '#4e6e8d'
    - '#7997b0'
    - '#f6fbfc'
  brandStrength: 0.5
  lightness: 0.07857682020403445
  saturation: 0.7858623203355819
  rhythmicContrast: 0.007962410803884268
purpose: []
