name: FTF Engineering
favicon: null
layout_spectrum: 0.38571
typography_spectrum: 0.434276235755533
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#354c6c'
    - '#c1c8ce'
    - '#4e6e8d'
    - '#7997b0'
    - '#f6fbfc'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.7858623203355819
  rhythmicContrast: 0.007962410803884268
purpose: []
