name: FTF Engineering
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9667743088211864
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.04386615473777056
  lightness: 0.9492773013189435
  saturation: 0.2514742468483746
  rhythmicContrast: 0.1722916050348431
purpose: []
